# Generated by Django 2.0.5 on 2018-05-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20180530_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='parent_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scrumboard.List'),
            preserve_default=False,
        ),
    ]
